FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential gcc-multilib g++-multilib nasm

COPY . /repo
WORKDIR /repo
RUN make install
WORKDIR /repo/sample
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libboost-dev
RUN make -j8
