FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential gcc-multilib g++-multilib nasm libboost-dev

COPY . /repo
WORKDIR /repo
RUN make install
WORKDIR /repo/sample
RUN make -j8

FROM ubuntu:22.04 as package
COPY --from=builder /repo/sample/bf64 /
